Allow scene nodes to have multiple scripts
FyroxEngine/Fyrox pull request #610
Opened 2024-02-20 19:34 UTC by dasimonde

Nodes can have multiple scripts now

2024-02-21 20:15 UTC, dasimonde commented
`error[E0499]: cannot borrow `context` as mutable more than once at a time
   --> src/engine/mod.rs:908:50
    |
903 |                     if let Some(node) = context.scene.graph.try_get_mut(handle_node) {
    |                                         ------------------- first mutable borrow occurs here
...
908 |                                 script.on_deinit(&mut context)
    |                                                  ^^^^^^^^^^^^ second mutable borrow occurs here
...
912 |                         for script in node
    |                                       ---- first borrow later used here

error[E0499]: cannot borrow `context` as mutable more than once at a time
   --> src/engine/mod.rs:921:50
    |
903 |                       if let Some(node) = context.scene.graph.try_get_mut(handle_node) {
    |                                           ------------------- first mutable borrow occurs here
...
912 |                           for script in node
    |  _______________________________________-
913 | |                             .secondary_scripts
914 | |                             .iter_mut()
915 | |                             .map(|i| i.0.as_mut())
916 | |                             .flatten()
    | |______________________________________- first borrow later used here
...
921 |                                   script.on_deinit(&mut context);
    |                                                    ^^^^^^^^^^^^ second mutable borrow occurs here

error[E0499]: cannot borrow `*context` as mutable more than once at a time
    --> src/engine/mod.rs:1067:30
     |
1052 |             let node = match context.scene.graph.try_get_mut(context.handle) {
     |                              ------------------- first mutable borrow occurs here
...
1067 |                 func(script, context);
     |                              ^^^^^^^ second mutable borrow occurs here
1068 |             };
1069 |             node.script = script;
     |             ---- first borrow later used here
...
1088 | define_process_node!(process_node, ScriptContext);
     | ------------------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `define_process_node` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0499]: cannot borrow `*context` as mutable more than once at a time
    --> src/engine/mod.rs:1078:35
     |
1052 |             let node = match context.scene.graph.try_get_mut(context.handle) {
     |                              ------------------- first mutable borrow occurs here
...
1071 |             for vec_script in node.secondary_scripts.iter_mut() {
     |                               --------------------------------- first borrow later used here
...
1078 |                 func(&mut script, context);
     |                                   ^^^^^^^ second mutable borrow occurs here
...
1088 | define_process_node!(process_node, ScriptContext);
     | ------------------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `define_process_node` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0499]: cannot borrow `*context` as mutable more than once at a time
    --> src/engine/mod.rs:1067:30
     |
1052 |             let node = match context.scene.graph.try_get_mut(context.handle) {
     |                              ------------------- first mutable borrow occurs here
...
1067 |                 func(script, context);
     |                              ^^^^^^^ second mutable borrow occurs here
1068 |             };
1069 |             node.script = script;
     |             ---- first borrow later used here
...
1089 | define_process_node!(process_node_message, ScriptMessageContext);
     | ---------------------------------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `define_process_node` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0499]: cannot borrow `*context` as mutable more than once at a time
    --> src/engine/mod.rs:1078:35
     |
1052 |             let node = match context.scene.graph.try_get_mut(context.handle) {
     |                              ------------------- first mutable borrow occurs here
...
1071 |             for vec_script in node.secondary_scripts.iter_mut() {
     |                               --------------------------------- first borrow later used here
...
1078 |                 func(&mut script, context);
     |                                   ^^^^^^^ second mutable borrow occurs here
...
1089 | define_process_node!(process_node_message, ScriptMessageContext);
     | ---------------------------------------------------------------- in this macro invocation
     |
     = note: this error originates in the macro `define_process_node` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0499]: cannot borrow `*scene` as mutable more than once at a time
    --> src/engine/mod.rs:1928:41
     |
1916 |                         if let Some(node) = scene.graph.try_get_mut(node_task_handler.node_handle) {
     |                                             ----------- first mutable borrow occurs here
...
1928 |                                         scene,
     |                                         ^^^^^ second mutable borrow occurs here
...
1940 |                                 node.script.replace(script);
     |                                 ---- first borrow later used here

error[E0499]: cannot borrow `*scene` as mutable more than once at a time
    --> src/engine/mod.rs:1953:45
     |
1916 |                         if let Some(node) = scene.graph.try_get_mut(node_task_handler.node_handle) {
     |                                             ----------- first mutable borrow occurs here
...
1943 |                             for vec_script in node.secondary_scripts.iter_mut() {
     |                                               --------------------------------- first borrow later used here
...
1953 |                                             scene,
     |                                             ^^^^^ second mutable borrow occurs here
`

2024-02-22 20:02 UTC, dasimonde commented
Everything should work now. The scripts for nodes in old scenes are loaded correctly now. Also I removed the Option type for the script buffer and combine script variable and the script buffer variable in one variable.

2024-02-22 20:08 UTC, mrDIMAS commented
Could you please also fix tests compilation and ensure that they pass? Also CI fails on documentation, run `cargo doc --all-features` and fix the warnings/errors too. This PR changes fundamental part of the engine and it must be perfect to not break existing projects.

2024-02-23 07:14 UTC, mrDIMAS requested changes

2024-02-23 07:14 UTC, mrDIMAS commented on src/scene/base.rs
> +    fn set_scripts_internal(&mut self, (index, script): (usize, Option<Script>)) -> Option<Script> {
This method is used in reflection-based access to `scripts` field and its signature must be `fn set_scripts_internal(&mut self, scripts: Vec<ScriptWrapper>) -> Vec<ScriptWrapper>`

2024-02-23 07:14 UTC, mrDIMAS commented on src/scene/base.rs
> +        if region.is_reading() {
These two branches of `if` are way too convoluted. To preserve backward compatibility all you need to do is:

```rust
let old_script: Option<Script> = None;
if region.is_reading() && old_script.visit("Script", region).is_ok() {
  self.scripts.push(ScriptWrapper(old_script));
  return;
}

self.scripts.visit("Scripts", region)?;
```

2024-02-23 07:14 UTC, mrDIMAS commented on src/scene/graph/mod.rs
> +    /// Searches for a **first** node with a secondary script of the given type `S` in the hierarchy starting from the
Remove `secondary`

2024-02-23 07:14 UTC, mrDIMAS commented on src/scene/graph/mod.rs
> +    pub fn try_get_secondary_script_component_of<C>(
Revert the name back.

2024-02-23 22:20 UTC, dasimonde commented
I have implemented all your change requests and all CI tests are green now

2024-02-24 08:06 UTC, mrDIMAS commented on src/scene/graph/mod.rs
> +    pub fn try_get_script_of<T>(&self, node: Handle<Node>, index: usize) -> Option<&T>
This method and every other that accepts `T` as a type argument, should search for a first script of type `T`. Similar to Unity's `GetComponent` (https://docs.unity3d.com/ScriptReference/GameObject.GetComponent.html) . Also the doc comment above the method should clearly state that this and other methods search for the first script of the given type.

2024-02-24 14:50 UTC, dasimonde commented
I hope everything is fine now

2024-02-24 15:20 UTC, mrDIMAS approved these changes

2024-02-24 15:21 UTC, merged