Fix for UI layout, including Grid and Text.
FyroxEngine/Fyrox pull request #698
Opened 2024-11-05 08:18 UTC by b-guild

I have implemented the WPF algorithm for laying out Grid widgets, including the resolution system for cases that involve some widgets being measured twice in order to determine some column widths.

I have expanded on the documentation for Grid and made the meanings of Strict, Auto, and Stretch more precise. A few grids in the editor were clearly using the wrong dimensions for their rows/columns, and I have made the necessary corrections so that the editor UI is not affected by these changes to Grid.

Part of these fixes to the editor's grid dimensions was fixing the dimensions of AssetItem's grid, and in order to make AssetItem work as it should I had to fix a problem with Text that was inserting some extra blank lines. This no longer happens, and I have added some unit tests that would have caught this bug. Now AssetItems can have letter wrap for their text widgets, allowing longer file names to be shown.

2024-11-05 10:51 UTC, mrDIMAS commented
Cool, I need some time to review it.

2024-11-06 11:13 UTC, mrDIMAS requested changes

2024-11-06 11:14 UTC, mrDIMAS commented
I checked the changes on my PC and found that World Viewer's items aren't filling all the space available for them: 
![изображение](https://github.com/user-attachments/assets/126570a7-6b3e-4b08-929a-447fcd00c0ee)

2024-11-06 21:36 UTC, b-guild commented
That should take care of it. It was easier than I thought. The changes to Grid do slightly modify its behavior, but they make it work the way it should. When something is supposed to fill the available space, it should be Stretch. When something is supposed to be at its natural size, it should be Auto. Often Auto seems to be used when it should be Stretch, and that is the source of these issues. In this case the Auto column was in Tree, and I changed it to Stretch.

2024-11-06 22:21 UTC, merged